# Production configuration using the new organized output structure
# This configuration uses the standardized directory hierarchy for all outputs

pipeline_id: "production_organized_output"
pipeline_name: "Climate Processing with Organized Output Structure"
description: "Full pipeline using the new organized output directory structure"
version: "1.0.0"
created_by: "Climate Pipeline Team"
created_date: "2024-12-17"

# Global pipeline settings
global_config:
  # Base paths - using organized structure
  base_output_path: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/organized"
  output_version: "v1.0"
  base_data_path: "/media/mihiarc/RPA1TB/CLIMATE_DATA/NorESM2-LM"
  enable_checkpointing: true
  checkpoint_dir: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/organized/checkpoints"
  
  # Performance settings
  max_parallel_stages: 1
  stage_timeout_minutes: 1440  # 24 hours
  
  # Logging
  log_level: "INFO"
  log_dir: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/organized/logs/pipeline"

# Pipeline stages
stages:
  - stage_id: "climate_means"
    stage_type: "means"
    description: "Calculate 30-year climate normals"
    enabled: true
    dependencies: []
    
    # Resource limits
    resource_limits:
      max_memory_gb: 60.0
      max_cpu_cores: 40
      max_runtime_minutes: 720
    
    # Stage configuration
    stage_config:
      # Variables to process
      variables: ["pr", "tas", "tasmax", "tasmin"]
      
      # Regions to process
      regions: ["CONUS", "AK", "HI", "PRVI", "GU"]
      
      # Scenarios
      scenarios: ["historical", "ssp245", "ssp585"]
      
      # Output path - will use organized structure
      # L1_climate_means/netcdf/{scenario}/{region}/
      output_base_path: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/organized/v1.0/L1_climate_means"
      
      # Processing parameters
      multiprocessing_workers: 32
      batch_size_years: 10
      max_memory_per_worker_gb: 1.8
      enable_rich_progress: true
      
      # Enable parallel processing
      enable_parallel_regions: true
      enable_parallel_variables: true
      max_parallel_regions: 2
      max_parallel_variables: 4
    
    # Output contract
    outputs:
      - output_id: "climate_means_output"
        output_type: "netcdf_files"
        data_contract:
          file_pattern: "{variable}_{region}_{scenario}_{period}_30yr_mean.nc"
          required_variables: ["pr", "tas", "tasmax", "tasmin"]
          spatial_coverage: ["CONUS", "AK", "HI", "PRVI", "GU"]
          temporal_coverage: "30-year normals"
          
  - stage_id: "climate_metrics"
    stage_type: "metrics"
    description: "Calculate county-level climate metrics"
    enabled: true
    dependencies: ["climate_means"]
    
    # Resource limits
    resource_limits:
      max_memory_gb: 40.0
      max_cpu_cores: 16
      max_runtime_minutes: 360
    
    # Stage configuration
    stage_config:
      # Input from previous stage (organized structure)
      input_means_path: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/organized/v1.0/L1_climate_means"
      
      # Output path - will use organized structure
      # L2_county_metrics/by_region/{region}/{format}/
      output_base_path: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/organized/v1.0/L2_county_metrics"
      
      # Variables to process
      variables: ["pr", "tas", "tasmax", "tasmin"]
      
      # Metrics to calculate
      metrics: ["mean", "std", "min", "max"]
      percentiles: [5, 10, 25, 50, 75, 90, 95]
      
      # Output formats
      output_formats: ["csv", "parquet", "netcdf"]
      
      # Processing options
      use_modern_boundaries: true
      weighted_by_area: true
      include_metadata: true
    
    # Output contract
    outputs:
      - output_id: "county_metrics_output"
        output_type: "tabular_data"
        data_contract:
          file_formats: ["csv", "parquet", "netcdf"]
          required_columns: ["GEOID", "NAME", "variable", "metric", "value"]
          spatial_resolution: "county"
          
  - stage_id: "validation"
    stage_type: "validation"
    description: "Validate data quality and generate reports"
    enabled: true
    dependencies: ["climate_metrics"]
    
    # Resource limits
    resource_limits:
      max_memory_gb: 20.0
      max_cpu_cores: 8
      max_runtime_minutes: 120
    
    # Stage configuration
    stage_config:
      # Input from previous stage
      metrics_output_path: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/organized/v1.0/L2_county_metrics"
      
      # Output directory - will use organized structure
      # L3_validation/reports/{validator_type}/
      output_dir: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/organized/v1.0/L3_validation"
      
      # Validators to run
      validators_to_run: ["qaqc", "spatial_outliers", "precipitation"]
      
      # Validation configuration
      validation_config:
        completeness_threshold: 0.95
        spatial_consistency_check: true
        temporal_consistency_check: true
        outlier_detection_method: "iqr"
        outlier_threshold: 3.0
        
      # Visualization options
      generate_maps: true
      generate_timeseries: true
      generate_distributions: true
      map_format: "png"
      figure_dpi: 300
    
    # Output contract
    outputs:
      - output_id: "validation_output"
        output_type: "validation_report"
        data_contract:
          report_format: "json"
          includes_visualizations: true
          quality_metrics: ["completeness", "consistency", "outliers"]

# Pipeline metadata
metadata:
  tags: ["production", "organized-output", "full-pipeline"]
  notes: |
    This configuration uses the new organized output structure:
    - L1_climate_means: 30-year climate normals
    - L2_county_metrics: County-level statistics
    - L3_validation: Quality assurance reports
    All outputs are versioned under v1.0 directory.