pipeline_id: "validation_conus_all_precip"
pipeline_name: "CONUS All Precipitation Files Validation"
pipeline_version: "1.0.0"
environment: "production"

# Data paths
base_data_path: "/media/mihiarc/RPA1TB/CLIMATE_DATA/NorESM2-LM"
temp_data_path: "/tmp/climate_processing"
log_path: "/var/log/climate/validation_conus_all_precip.log"

# Global resource limits
global_resource_limits:
  max_memory_gb: 32.0
  max_cpu_cores: 16
  max_processing_time_hours: 4.0

# Global configuration
global_config:
  data_source: "NEX-GDDP-CMIP6"
  model: "NorESM2-LM"
  climate_normals_period: 30
  output_format: "json"
  enable_caching: true
  cache_directory: "/tmp/climate_cache"

# Pipeline stages
stages:
  # Validation Stage for all CONUS Precipitation files
  - stage_id: "validation"
    stage_type: "validation"
    stage_name: "CONUS All Precipitation QA/QC"
    package_name: "county_climate.validation.integration"
    entry_point: "validation_stage_handler_fixed"
    trigger_type: "manual"
    
    # Resource limits
    resource_limits:
      max_memory_gb: 24.0
      max_cpu_cores: 12
      max_processing_time_hours: 3.0
      priority: 5
    
    # Retry configuration
    retry_attempts: 2
    retry_delay_seconds: 120
    
    # Stage-specific configuration
    stage_config:
      # Process all CONUS precipitation files using wildcard pattern
      metrics_output_path: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/metrics/pr_CONUS_*_county_metrics.csv"
      
      # Output directory for validation results
      output_dir: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/validation/conus_all_precipitation"
      
      # Validators to run
      validators_to_run: ["spatial"]  # Only spatial works with metrics format
      
      # Enable visualizations
      run_visualizations: false  # Skip for now as they expect different columns
      
      # Batch processing settings
      batch_processing:
        enabled: true
        batch_size: 10  # Process 10 files at a time
        
      # Validation configuration specific to CONUS
      validation_config:
        # Data expectations for CONUS
        expected_counties: 3109  # CONUS has 3109 counties
        expected_scenarios: ["historical", "ssp245", "ssp585"]
        expected_region: "CONUS"
        
        # Focus on precipitation variable
        focus_variable: "pr"
        
        # Precipitation-specific thresholds for CONUS
        precipitation_thresholds:
          min_annual_precipitation: 50.0     # mm (driest areas)
          max_annual_precipitation: 5000.0   # mm (wettest areas)
          
        # Outlier detection thresholds
        iqr_multiplier: 1.5        # Standard for CONUS
        z_score_threshold: 3.0     # Standard threshold
        modified_z_threshold: 3.5  # Standard MAD threshold
        
        # Missing data thresholds
        max_missing_overall: 5.0
        max_missing_per_metric: 10.0
        max_missing_per_county: 15.0
        
        # Output settings
        save_plots: false
        create_summary_report: true
        aggregate_results: true  # Combine results across all files
        
        # Validation modules to run
        run_completeness_check: false  # Disabled - expects different columns
        run_spatial_check: true
        run_temporal_check: false      # Disabled - expects year column
        run_logical_check: false       # Disabled - expects specific columns
        run_plausibility_check: false  # Disabled - expects specific columns
        run_outlier_detection: true
        run_visualization: false       # Disabled - expects different columns
        run_precipitation_specific: false  # Disabled - expects different columns

# Pipeline trigger configuration
triggers:
  - trigger_id: "manual_trigger"
    trigger_type: "manual"
    stages: ["validation"]

# Processing profiles
processing_profiles:
  - profile_id: "validation_only"
    profile_name: "Validation Only"
    stages: ["validation"]