pipeline_id: "validation_alaska_precip"
pipeline_name: "Alaska Precipitation Validation"
pipeline_version: "1.0.0"
environment: "production"

# Data paths
base_data_path: "/media/mihiarc/RPA1TB/CLIMATE_DATA/NorESM2-LM"
temp_data_path: "/tmp/climate_processing"
log_path: "/var/log/climate/validation_alaska_precip.log"

# Global resource limits
global_resource_limits:
  max_memory_gb: 16.0
  max_cpu_cores: 8
  max_processing_time_hours: 2.0

# Global configuration
global_config:
  data_source: "NEX-GDDP-CMIP6"
  model: "NorESM2-LM"
  climate_normals_period: 30
  output_format: "json"
  enable_caching: true
  cache_directory: "/tmp/climate_cache"

# Pipeline stages
stages:
  # Validation Stage for Alaska Precipitation
  - stage_id: "validation"
    stage_type: "validation"
    stage_name: "Alaska Precipitation QA/QC"
    package_name: "county_climate.validation.integration"
    entry_point: "validation_stage_handler"
    trigger_type: "manual"
    
    # Resource limits
    resource_limits:
      max_memory_gb: 16.0
      max_cpu_cores: 8
      max_processing_time_hours: 1.0
      priority: 5
    
    # Retry configuration
    retry_attempts: 1
    retry_delay_seconds: 60
    
    # Stage-specific configuration
    stage_config:
      # Input metrics files - updated for new time series format
      metrics_time_series_path: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/metrics_timeseries"
      regions: ["AK"]
      variables: ["pr"]
      
      # Output directory for validation results
      output_dir: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/validation/alaska_precipitation"
      
      # Validators to run - focusing on precipitation
      validators_to_run: ["precipitation", "qaqc", "spatial"]
      
      # Enable visualizations
      run_visualizations: true
      
      # Validation configuration specific to Alaska
      validation_config:
        # Data expectations for Alaska
        expected_counties: 30  # Alaska has 30 counties/boroughs
        expected_scenarios: ["historical", "ssp245", "ssp585"]
        expected_region: "AK"
        
        # Focus on precipitation variable
        focus_variable: "pr"
        
        # Precipitation-specific thresholds for Alaska
        precipitation_thresholds:
          # Alaska has unique precipitation patterns
          min_annual_precipitation: 100.0    # mm (some interior regions are very dry)
          max_annual_precipitation: 5000.0   # mm (southeast Alaska gets heavy rainfall)
          max_precipitation_days_50mm: 200   # Days with >50mm precipitation
          max_precipitation_days_100mm: 100  # Days with >100mm precipitation
          
        # Outlier detection thresholds
        iqr_multiplier: 2.0        # More lenient for Alaska's diverse climate
        z_score_threshold: 3.5     # Slightly higher threshold
        modified_z_threshold: 4.0  # Account for extreme variations
        
        # Temporal consistency thresholds
        max_year_to_year_precip_change: 800.0  # mm (higher for Alaska)
        
        # Missing data thresholds
        max_missing_overall: 5.0
        max_missing_per_metric: 10.0
        max_missing_per_county: 15.0
        
        # Alaska-specific settings
        alaska_specific:
          # Account for diverse climate zones
          enable_climate_zone_analysis: true
          # Check for dateline issues
          check_dateline_consistency: true
          # Validate against known dry interior vs wet coastal patterns
          validate_regional_patterns: true
        
        # Output settings
        save_plots: true
        plot_dpi: 300
        create_summary_report: true
        
        # Validation modules to run
        run_completeness_check: true
        run_spatial_check: true
        run_temporal_check: true
        run_logical_check: true
        run_plausibility_check: true
        run_outlier_detection: true
        run_visualization: true
        run_precipitation_specific: true

# Pipeline trigger configuration
triggers:
  - trigger_id: "manual_trigger"
    trigger_type: "manual"
    stages: ["validation"]

# Processing profiles
processing_profiles:
  - profile_id: "validation_only"
    profile_name: "Validation Only"
    stages: ["validation"]