pipeline_id: "means_conus_ssp585_flexible"
pipeline_name: "CONUS SSP585 Climate Means Processing (Flexible)"
pipeline_version: "1.0.0"
environment: "production"

# Data paths
base_data_path: "/media/mihiarc/RPA1TB/CLIMATE_DATA/NorESM2-LM"
temp_data_path: "/tmp/climate_processing"
log_path: "./conus_ssp585_flexible_processing.log"

# Global resource limits
global_resource_limits:
  max_memory_gb: 85.0
  max_cpu_cores: 52
  max_processing_time_hours: 12.0

# Global configuration
global_config:
  data_source: "NEX-GDDP-CMIP6"
  model: "NorESM2-LM"
  climate_normals_period: 30
  output_format: "netcdf4"
  compression_level: 4
  enable_caching: false

# Pipeline stages
stages:
  # Climate Means Processing Stage using flexible handler
  - stage_id: "climate_means"
    stage_type: "means"
    stage_name: "CONUS SSP585 Climate Means (Flexible)"
    package_name: "county_climate.means.integration"
    entry_point: "flexible_means_stage_handler"  # Use flexible handler
    trigger_type: "manual"
    
    # Resource limits
    resource_limits:
      max_memory_gb: 80.0
      max_cpu_cores: 50
      max_processing_time_hours: 10.0
      priority: 10
    
    # Retry configuration
    retry_attempts: 2
    retry_delay_seconds: 300
    
    # Stage-specific configuration
    stage_config:
      # Process SSP585 for CONUS with flexible handler
      variables: ["pr", "tas", "tasmax", "tasmin"]
      regions: ["CONUS"]
      scenarios: ["ssp585"]  # This will actually process SSP585!
      
      # Climate model configuration
      model_id: "NorESM2-LM"
      
      # Ultra-high performance settings
      multiprocessing_workers: 56
      batch_size_years: 10
      max_memory_per_worker_gb: 3.5
      enable_rich_progress: true
      
      # Output paths
      output_base_path: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/means"
      
    # Output configuration
    output_config:
      base_path: "/media/mihiarc/RPA1TB/CLIMATE_OUTPUT/means"
      create_manifest: true
      overwrite_existing: false
      file_naming_pattern: "{variable}_{region}_{scenario}_{target_year}_{period_type}_climate_normal.nc"

# Pipeline execution settings
execution_config:
  mode: "sequential"
  stop_on_error: false
  enable_checkpointing: true
  checkpoint_interval_minutes: 5
  restart_from_checkpoint: false
  
# Monitoring configuration
monitoring_config:
  enable_resource_monitoring: true
  monitoring_interval_seconds: 30
  alert_on_resource_threshold: true
  resource_alert_thresholds:
    memory_percent: 90
    cpu_percent: 95
  
# Notification settings
notification_config:
  enable_notifications: false
  notification_types: ["email", "slack"]